### ISSUE TITLE
Incompatible With .NET Core and EF Core Version 2.0

### ISSUE THREAD

**Issue by ghost** [shawnwildermuth/WebAPICoreResources#1]
This repository contains companion source code for the Pluralsight course:

Implementing and Securing an API with ASP.NET Core:
https://app.pluralsight.com/library/courses/aspdotnetcore-implementing-securing-api

Has anyone figured out how to get this code to work in .NET Core 2.0 and EF Core 2.x?

If so, please help.

Thanks.

Jonathan

**Comment by shawnwildermuth** [comment]
This course is going to be updated soon. ASP.NET Core 2.1 has changed quite a lot for APIs. You can see my full ASP.NET Core course (recently updated to 2.1) that shows lots of the changes until this course is updated.

**Comment by ghost** [comment]
I see your new course now. I will check it out. Thanks Shawn.

- Jonathan
